height_range = ['5\'1\"', '5\'2\"', '5\'3\"', '5\'4\"', '5\'5\"', '5\'6\"', '5\'7\"', '5\'8\"', '5\'9\"', '5\'10',
                '5\'11', '6\'0\"', '6\'1\"', '6\'2\"', '6\'3\"', '6\'4\"', '6\'5\"', '6\'6\"']

dumb_sizes = ['free', 'standard', 'regular']

shadecard_bricks = ["eye pencil", "eye shadow", "lip liner", "eye liner", "lipstick", "lips gloss", "make-up base",
                    "nail enamel", "mascara", "compact powder", "blusher",
                    "lip balm", "lip care", "loose powder", "concealer & corrector", "face highlighter", "highlighter",
                    "nail art", "kajal", "nail top & base coat", "eye palette"]
beauty = ["strech denim"]  # beauty and fragnances
toys = ["100% linen"]
actsprts = ["polyester", "polyester spandex", "poly cotton"]
jewellery = ["bones", "pu", "metal", "leather/brass", "92.5 silver", "pewter", "leather", "tungsten", "thread",
             "steel", "crystal", "sterling silver", "copper", "brass & leather", "swarovski elements",
             "semi-precious stones", "copper alloy", "resin", "wooden", "titanium", "metal/leather", "brass & beads",
             "69%steel, 40%acrylic", "alloy & acrylic", "wood", "beads", "100%zinc", "brass metal", "alloy", "acrylic",
             "brass", "ceramic", "na", "polyester", "stainless steel", "14 karat gold", "german silver", "cz", "stone",
             "glass beads", "fabric", "shell", "lace", "silver", "18 karat gold", "plastic", "clay",
             "316l stainless steel", "pearl", "80%metal, 20%glass", "92.5 sterling silver", "leather/beads", "nylon",
             "faux leather", "diamond", "bronze", "silver+alloy", "gold"]
home = ["micro fibre", "iron", "metal", "cotton silk", "70%polyester 30%cotton", "poly velvet",
        "65% polyester 35% cotton", "terry", "100% polyester", "poly dupion", "micro fabric", "cotton vicsose",
        "polyster", "polysilk", "polyester wool", "memory foam", "polycotton", "polypropylene", "taffeta",
        "60%cotton 40%polyester", "cotton blend with polyfill", "polyester viscose", "100% cotton", "soyabean",
        "100% cotton with poly filling", "linen", "suede", "wool", "wood", "na", "ceramic", "poly viscose",
        "65%polyester 35%viscose", "fibre", "microfibre", "polyester", "fleece", "stainless steel", "spandex",
        "cotton blend", "polyester filling", "chenille", "polyester satin", "100% satin cotton",
        "100% mercerized cotton", "100% cotton with polyfill", "rubber", "pvc", "velvet", "80%cotton 20%polyester",
        "tencel", "silk", "jute", "microfibre filling", "rayon", "plastic", "60% viscose 40% polyester", "leatherette",
        "cotton", "outer cotton inner polyester", "nylon", "viscose", "cotton satin", "70%cotton 30%polyester",
        "60%polyester 40%cotton"]
acc = ["900d polyester x 600d polyester", "metal", "acetate blend", "sheet", "leather", "synthetic", "polyester fabric",
       "1680d polyester", "neoprene", "denim", "polyurethane", "cloth", "tough polyester fabric", "resin", "tetron",
       "canvas/leather", "600d polyester", "alloy & acrylic", "polyamide", "acrylic", "900d polyester", "flex",
       "cotton canvas", "dupion silk", "presspro technology", "jute", "pearl", "leatherette", "viscose", "420d nylon",
       "premium diamond ripstop fabric", "premium polynlyon fabric", "aluminium", "textreme 6.6", "shimmer", "raw silk",
       "poly", "poly shantoon/shimmer", "net", "wooden", "fur", "wool", "alloy", "na", "brass", "polyester",
       "canvas/pu", "tatron", "fabric", "450 hd polyoxford", "twill fabric", "nylon honeycomb x 600 d polyester",
       "plastic moulded footwear", "faux leather", "t-square rip", "brocade", "polycarbonate",
       "stylish printed jaquard fabric", "propionate", "synthetic leather", "t-rip light", "cotton silk",
       "tough polypropylene shell", "canvas", "cuzy nylon fabric", "210t nylon ripstop", "80% wool 20% nylon",
       "100% polyurethane", "lacquer", "fibre", "stainless steel", "canvas and leather", "shell", "pvc", "velvet",
       "plastic", "cotton", "daneir fabric", "texamid 11.1", "pu", "acetate", "lightweight and tough polycarbonate",
       "silicon", "poly/shimmer", "steel", "tr-90", "others", "polypropylene", "artificial leather", "ripstop fabric",
       "canvas & leather", "titanium", "suede", "wood", "non leather", "ceramic", "vegan cow leather",
       "630d polyester + 420d dobby", "dobby nylon", "webbing", "tough polypropylene", "rubber", "silk", "pu/canvas",
       "nylon", "satin"]
apparels = ["metal", "100% acrylic", "viscose jersey", "acetate blend", "lyocell", "cotton voile", "leather",
            "cotton poly", "polyamide spandex(stretchable)", "synthetic", "tussar silk", "poly dupion", "chambrey",
            "nylon & cotton", "polyster", "cotton linen", "denim", "nylon spandex(stretchable)", "100% viscose",
            "ramie", "nylon spandex", "polyurethane", "velour", "95%terelene 5%spandex(stretchable)", "pique",
            "linen cotton", "twill spandex(stretchable)", "wool blend", "cotton fleece", "crepe jersey",
            "polyester nylon", "95% polyester 5%spandex", "brasso silk", "100%viscose", "poly georgette",
            "artificial silk", "net brasso", "cvc", "poplin", "poly linen", "cotton knit", "polyamide", "acrylic",
            "organic cotton eucalyptus blend", "polyknit spandex(stretchable)", "combed cotton", "viscose modal",
            "flex", "jersy", "viscose jacquard", "silk blend", "poly silk", "dupion silk",
            "87% nylon + 13% lycra(elastane)", "polyester satin", "art silk", "cotton 96% elastane 4%",
            "70% cotton, 30% polyester", "cotton polyester", "jute", "poly cotton", "jacquard crepe",
            "poly viscose wool", "net and jacquard", "woven", "chanderi silk", "crochet", "cambric", "leatherette",
            "cottonpoly spandex(stretchable)", "viscose", "micro fibre", "tafetta", "banarasi",
            "80% acrylic, 20% cotton", "net and chiffon", "poly rayon spandex", "cotton satin spandex(stretchable)",
            "twill lycra", "jute silk", "brocade silk", "cotton modal", "georgette crepe",
            "cotton polyamide spandex(stretchable)", "cotton spandex(stretchable)",
            "95%polyester 5%spandex(stretchable)", "shimmer", "cotton poly spandex", "georgette",
            "98% cotton 2% spandex", "polycotton", "poly", "raw silk", "organic cotton spandex",
            "cotton 85% viscose 10% elastane 5%", "cotton spandex (stretchable)", "100% organic cotton", "strech denim",
            "gorgette", "net", "100% cotton", "fur", "linen", "bamboo cotton blend", "wool",
            "92%cotton 8%spandex(stretchable)", "viscose blend", "polyester silk", "handloom silk", "polyester blend",
            "poly viscose", "tussar", "brass", "alloy", "polycotton spandex(stretchable)", "organza", "polyester",
            "80% cotton, 20% polyester", "elastane(stretchable)", "bamboo organic cotton blend", "viscose lycra",
            "80% acrylic 20% wool", "synthetic stretch", "micro poly blend", "sheer", "super net",
            "96%polyester 4%spandex(stretchable)", "nylon lycra", "net jacquard", "100% nylon", "poly viscose nylon",
            "80% cotton, 20% wool", "viscose spandex(stretchable)", "actylic", "50%cotton 50%polyester",
            "chanderi cotton", "polyamide spandex", "faux leather", "corduroy", "brocade",
            "95%viscose 5%spandex(stretchable)", "polyester spandex", "net and georgette", "cotton silk", "mesh",
            "canvas", "rayon spandex(stretchable)", "100% polyester", "shantoon", "beads", "cotton 98% elastane 2%",
            "denim spandex(stretchable)", "acrowool", "cotton viscose", "blended", "dobby", "terelyne rayon",
            "poly viscose elastane", "65%polyester,35%cotton", "95% cotton 5% spandex", "polyester viscose",
            "cotton jersey", "rayon blend", "bhagalpuri silk", "100% cotton poplin", "chiffon", "bamber",
            "75%polyester 23%viscose 2%lycra", "polyester cotton", "jersey", "acrylic wool", "polyester georgette",
            "100% polyurethane", "fleece", "cotton rich", "cotton stretch", "polyester crepe", "micro", "poly wool",
            "cotton blend", "sequins fabric", "microfibre", "100%cotton", "crepe silk", "polyster chiffon",
            "92/8 viscose lycra", "linen blend", "viscose spandex", "80%cotton 20%polyester", "velvet", "pvc",
            "96%viscose 4%spandex(stretchable)", "plastic", "jaquard", "90%polyester 10%spandex(stretchable)", "bamboo",
            "crepe", "cotton 97% elastane 3%", "cotton", "80/20 cotton wool", "cotton lawn", "net and silk", "chanderi",
            "60/40 polycotton", "twill spandex", "pu", "acetate", "poly satin", "silicon", "woolen", "net and brasso",
            "terry", "steel", "polyester lycra", "modal blend", "knit", "100% wool", "poly chiffon", "stretch cotton",
            "others", "twill", "nylon blend", "60%cotton 40%polyester", "brasso", "banarsi silk", "cotton & denim",
            "taffeta", "100% linen", "polyester chiffon", "95/5 cotton lycra", "polyester spandex(stretchable)",
            "cotton rayon", "suede", "tissue", "viscose silk", "organic cotton", "net and  georgette", "poly crepe",
            "65%polyester 35%viscose", "tweed", "polyester viscose spandex(stretchable)", "linen/cotton", "teflon",
            "wool rich", "polyester fleece", "60% cotton/40% polyester", "bamberg", "95%cotton 5%spandex(stretchable)",
            "acrylic blend", "silk", "tencel", "60% polyester, 40% cotton", "rayon",
            "80%viscose 13%nylon 7%spandex(stretchable)", "polyamide blend", "rayon polyester", "viscose jersy",
            "flannel", "wool cotton spandex(stretchable)", "modal", "nylon", "cotton satin", "chandelier lace",
            "terry rayon", "satin"]
no_vitals = ["belt", "boxers", "briefs", "caps", "combo", "cufflinks", "handkerchief", "hats", "mufflers", "scarves",
             "socks", "ties", "trunks", "vests", "wallet", "wristbands", "dupattas", "shawls", "shrugs", "stoles",
             "pocket square"]

footwear_mat = ["plastic moulded footwear", "cotton", "pvc", "non leather", "leather", "na"]

bag_list = ["sling bag", "backpack", "duffel bags", "bags", "laptop bag", "laptop backpack",
            "messenger bags", "shopping bag", "school bag", "travelling bag", "sports bag",
            "laptop briefcase", "multiutility bag"]

# map of categories against the material details
data_map = {
    "acc": acc,
    "jewellry": jewellery,
    "apparel": apparels,
    "home": home,
    "footwear": footwear_mat,
    "beauty": beauty,
    "fragrances": beauty,
    "toys": toys,
    "actsprts": actsprts
}
